export const prompts = [
    "The quick brown fox jumps over the lazy dog, showcasing every letter of the English alphabet in a concise sentence.",
    "To be or not to be, that is the question - a timeless contemplation on life, death, and the human condition, spoken by Hamlet in Shakespeare's renowned play.",
    "All that glitters is not gold, a cautionary proverb reminding us that appearances can be deceiving and true value lies beyond superficial shine.",
    "A journey of a thousand miles begins with a single step, Lao Tzu's wisdom encouraging us to embark on even the most daunting tasks by taking that initial stride.",
    "Where there's a will, there's a way, an optimistic adage suggesting that determination and resourcefulness can overcome obstacles.",
    "Look before you leap, but don't hesitate too long. This advice promotes careful consideration while also urging us to avoid paralysis by analysis.",
    "Actions speak louder than words, so let your deeds do the talking. This emphasizes the importance of demonstrating intentions through tangible actions rather than empty promises.",
    "Better late than never, but strive for punctuality. While acknowledging that lateness is sometimes unavoidable, it emphasizes the value of timeliness and respect for others' schedules.",
    "Don't count your chickens before they hatch, as unforeseen circumstances can arise and disrupt even the best-laid plans.",
    "Early to bed and early to rise, makes a man healthy, wealthy, and wise, according to Benjamin Franklin, promoting a disciplined lifestyle as a path to success.",
    "Practice makes perfect, so continue honing your skills diligently and consistently to achieve mastery.",
    "Two wrongs don't make a right; seeking revenge only perpetuates the cycle of negativity and prevents true resolution.",
    "The pen is mightier than the sword, demonstrating the power of communication and ideas to influence and change the world.",
    "When in Rome, do as the Romans do, adapting to local customs and traditions to foster understanding and respect during travels.",
    "A picture is worth a thousand words, conveying complex emotions and narratives visually, often more effectively than language can express.",
    "Birds of a feather flock together, as people tend to gravitate towards like-minded individuals, forming communities based on shared interests and values.",
    "Honesty is the best policy, fostering trust and building strong relationships based on authenticity and integrity.",
    "Necessity is the mother of invention, driving innovation and problem-solving by inspiring creative solutions to pressing challenges.",
    "The early bird catches the worm, emphasizing the advantages of proactivity and taking initiative to seize opportunities before others.",
    "Time and tide wait for no man, highlighting the importance of seizing opportunities and managing time effectively, as it is a finite resource.",
    "A stitch in time saves nine, advocating for preventative measures and addressing problems promptly to avoid more extensive repairs later on.",
    "Make hay while the sun shines, urging us to capitalize on favorable conditions and make the most of opportunities while they are available.",
    "Variety is the spice of life, celebrating diversity and embracing new experiences to enrich our lives and broaden our perspectives.",
    "All's well that ends well, suggesting that a positive outcome can redeem past difficulties and challenges, ultimately leading to a satisfying conclusion."
];